name: Snake Animation

on:
  schedule:
    - cron: "0 */6 * * *"  # Atualiza a cada 6 horas
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar Snake Game
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg

      - name: Commit e push
        uses: EndBug/add-and-commit@v9
        with:
          message: "Atualizando a cobrinha"
          add: "dist/snake.svg"
          push: true
